# Generated by Django 4.1.5 on 2023-01-19 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest_insure',
            name='insure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insures_invest_insure', to='insurances.insurance'),
        ),
        migrations.AlterField(
            model_name='invest_insure',
            name='invest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_invest_insure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_insure',
            name='insure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insures_user_insure', to='insurances.insurance'),
        ),
        migrations.AlterField(
            model_name='user_insure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_user_insure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='invest_insure',
            unique_together={('invest', 'insure')},
        ),
        migrations.AlterUniqueTogether(
            name='user_insure',
            unique_together={('user', 'insure')},
        ),
    ]
